app_4_website/pty_oprtn_cd_clssfctn/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField


class PtyOprtnCdClssfctnForm(FlaskForm):
    trnsct_ctg = SelectField('Kategoria transakcji', choices=[])
    trnsct_sctg = SelectField('Podkategoria transakcji', choices=[])
    submit = SubmitField('Wykonaj')

app_4_website/balances/routes.py
from flask import Blueprint, render_template, request
from app_4_website.balances.utils import MonthlyDtlBal, YearlyDtlBal, MonthlyCtgBal
from datetime import datetime

balances = Blueprint('balances', __name__)


@balances.route("/monthly_dtl_bal")
@balances.route("/monthly_dtl_bal_<int:p_year>_<int:p_month>")
def monthly_dtl_bal(p_year=datetime.today().year, p_month=datetime.today().month):
    page = request.args.get('page', 1, type=int)

    colors = [
        "#F7464A", "#46BFBD", "#FDB45C", "#FEDCBA",
        "#ABCDEF", "#DDDDDD", "#ABCABC", "#4169E1",
        "#C71585", "#FF4500", "#FEDCBA", "#46BFBD"]

    v_list = MonthlyDtlBal(p_year, p_month).summary_paginated(page=page)
    v_ctg_chart_data = MonthlyCtgBal(p_year, p_month).query_result_all('2', 'N')    # only expenses - 2; not detailed - N
    # v_sctg_chart_data = MonthlyCtgBal(p_year, p_month).query_result_all('2', 'T')

    v_ctg_label_list = []
    v_ctg_value_list = []

    for item in v_ctg_chart_data:
        v_ctg_label_list.append(item.GROUP_NM)
        v_ctg_value_list.append(item.TRNSCTN_SUM)

    return render_template('monthly_dtl_bal.html', title='PODSUMOWANIE MIESIĄCA', p_year=p_year, p_month=p_month, v_list=v_list, labels=v_ctg_label_list, values=v_ctg_value_list, colors=colors)


@balances.route("/yearly_dtl_bal")
def yearly_dtl_bal(p_year=datetime.today().year):
    return render_template('yearly_dtl_bal.html', title='YEARLY DETAIL BAL', v_list=YearlyDtlBal(p_year).summary_all())

app_4_website/main/routes.py
from flask import Blueprint, render_template
from app_4_website.balances.utils import YearlyBal, MonthlyBal
from app_4_website.import_log.utills import get_last_operation_dt
from datetime import date

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home(p_year=date.today().year, p_month=date.today().month):
    monthly_bal = MonthlyBal(p_year, p_month).summary_all()
    yearly_bal = YearlyBal(p_year).summary()
    v_loaded_operation_dt = get_last_operation_dt()

    return render_template('home.html', monthly_bal=monthly_bal, yearly_bal=yearly_bal, v_loaded_operation_dt=v_loaded_operation_dt)

app_4_website/pty_oprtn_cd_clssfctn/routes.py
from flask import Blueprint, render_template, jsonify, request, redirect, flash, url_for
from app_4_website.pty_oprtn_cd_clssfctn.utils import PtyOprtnClssfctnCdUtils
from app_4_website.pty_oprtn_cd_clssfctn.forms import PtyOprtnCdClssfctnForm
from app_4_website.pty.utils import Pty
from app_4_website.common.utils import redirect_url
from app_4_website.dictionaries.utils import DictTrnsctnSctgUtils, DictOperationTpMapUtils
from datetime import datetime

pocc = Blueprint('pocc', __name__)


@pocc.route("/pty_oprtn_cd_clssfctn", methods=['GET', 'POST'])
@pocc.route("/pty_oprtn_cd_clssfctn/yearly_<int:p_year>", methods=['GET', 'POST'])
@pocc.route("/pty_oprtn_cd_clssfctn/<int:p_year>_<int:p_month>", methods=['GET', 'POST'])
@pocc.route("/pty_oprtn_cd_clssfctn/notfilled_<int:p_notfilled>", methods=['GET', 'POST'])
def pty_oprtn_cd_clssfctn(p_year=None, p_month=None, p_notfilled=None):
    page = request.args.get('page', 1, type=int)
    v_pagination_list = PtyOprtnClssfctnCdUtils().get_pty_oprtn_cd_clssfctn_rows(p_year=p_year, p_month=p_month, p_notfilled=p_notfilled, page=page)

    if request.method == 'POST':
        a = request.form.get('pocc_select')

        if a == 'monthly':
            return redirect(url_for('pocc.pty_oprtn_cd_clssfctn', p_year=datetime.today().year, p_month=datetime.today().month))
        elif a == 'yearly':
            return redirect(url_for('pocc.pty_oprtn_cd_clssfctn', p_year=2020))
        elif a == 'all':
            return redirect(url_for('pocc.pty_oprtn_cd_clssfctn'))
        elif a == 'notfilled':
            return redirect(url_for('pocc.pty_oprtn_cd_clssfctn', p_notfilled=1))

    return render_template("pty_oprtn_cd_clssfctn.html", title="KATEGORYZACJA TRANSAKCJI",
                           v_val_list=v_pagination_list,
                           p_year=p_year,
                           p_month=p_month,
                           p_notfilled=p_notfilled)


@pocc.route("/pty_oprtn_cd_clssfctn_edit/<int:p_pty_id>_<int:p_oprtn_cd>", methods=['GET', 'POST'])
def pty_oprtn_cd_clsfctn_edit(p_pty_id, p_oprtn_cd):
    form = PtyOprtnCdClssfctnForm()

    v_oprtn_ctg = DictOperationTpMapUtils().get_oprtn_cd_oprnt_ctg_id(p_oprtn_cd)
    v_oprtn_ctg = v_oprtn_ctg.oprtn_ctg_id

    v_trnsctn_ctg_vals = DictTrnsctnSctgUtils().get_trnsctn_ctg_list(None, v_oprtn_ctg)
    form.trnsct_ctg.choices = [(Item.dict_val_id, Item.dict_val_val) for Item in v_trnsctn_ctg_vals]

    v_pty_data = Pty(p_pty_id).get_pty_data()

    v_data = {"pty_nm": v_pty_data.pty_nm,
              "pty_address": v_pty_data.pty_addrss,
              "pty_city": v_pty_data.pty_city,
              "pty_ctry": v_pty_data.pty_ctry,
              "pty_acn": v_pty_data.pty_acn,
              "oprtn_ctg": v_oprtn_ctg
              }

    if request.method == 'POST':
        v_trnsctn_ctg = form.trnsct_ctg.data
        v_trnsctn_sctg = form.trnsct_sctg.data

        PtyOprtnClssfctnCdUtils(p_pty_id, p_oprtn_cd).update_pty_oprtn_clssfctn_cd_table(v_trnsctn_ctg, v_trnsctn_sctg)
        flash("Poprawnie zaktualizowano wpis", 'success')
        return redirect(redirect_url())

    return render_template("pty_oprtn_cd_clssfctn_edit.html", title="KLASYFIKACJA", v_data=v_data, form=form)


@pocc.route("/pty_oprtn_cd_clssfctn_edit/get_trnsctn_sctg_list/<p_trnsctn_ctg_id>_<p_oprtn_ctg>")
def get_trnsctn_sctg_list(p_trnsctn_ctg_id, p_oprtn_ctg):
    dict_array = []

    dict_vals = DictTrnsctnSctgUtils().get_trnsctn_sctg_list(p_trnsctn_ctg_id, p_oprtn_ctg)

    for item in dict_vals:
        dictObj = {}
        dictObj['dict_val_id'] = item.dict_val_id
        dictObj['dict_val_val'] = item.dict_val_val
        dict_array.append(dictObj)

    return jsonify({'dict_values': dict_array})

app_4_website/templates/add_dict_value.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h1>{{ title }}</h1>
    </div>
    <div class="form">

    <form method = 'POST' action = "">
            {{ form.hidden_tag() }}
            <fieldset class = 'form-group'>

                <div class="row">
                    <div class='col-25'>
                        {{ form.dict_id.label(class="form-control-label") }}
                    </div>
                    <div class='col-75'>
                        <input class="form-control" id="disabledInput1" type="text" placeholder=" {{ data['dict_id'] }}" disabled>
                    </div>
                </div>

                <div class="row">
                    <div class='col-25'>
                    {{ form.dict_val_id.label(class="form-control-label") }}
                </div>
                <div class='col-75'>
                    <input class="form-control" id="disabledInput2" type="text" placeholder=" {{ data['dict_val_id'] }}" disabled>
                </div>
                </div>

                <div class="row">
                    <div class='col-25'>
                    {{ form.dict_val_val.label(class="form-control-label") }}
                </div>
                <div class='col-75'>
                    {{ form.dict_val_val }}
                    </div>
                </div>

                <div class="row">
                    <div class='col-25'>
                    {{ form.dict_val_crt_dt.label(class="form-control-label") }}
                </div>
                <div class='col-75'>
                    <input class="form-control" id="disabledInput3" type="text" placeholder=" {{ data['dict_val_crt_dt'] }}" disabled>
                    </div>
                </div>

                {% if data['dict_tp'] == '2'%}
                <hr>
                <div class="row">
                    <div class='col-25'>
                    {{ form.rltd_dict_nm_1.label(class="form-control-label") }}
                </div>
                <div class="col-75">
                        {{ form.rltd_dict_nm_1 }}
                </div>
                </div>
                <div class="row">
                    <div class='col-25'>
                    {{ form.rltd_dict_val_1.label(class="form-control-label") }}
                </div>
                <div class="col-75">
                    {{ form.rltd_dict_val_1 }}
                </div>
                </div>
                <hr>
                <div class="row">
                    <div class='col-25'>
                    {{ form.rltd_dict_nm_2.label(class="form-control-label") }}
                </div>
                <div class="col-75">
                        {{ form.rltd_dict_nm_2 }}
                </div>
                </div>
                <div class="row">
                    <div class='col-25'>
                    {{ form.rltd_dict_val_2.label(class="form-control-label") }}
                </div>
                <div class="col-75">
                    {{ form.rltd_dict_val_2 }}
                </div>
                </div>
                <hr>
                <div class="row">
                    <div class='col-25'>
                    {{ form.rltd_dict_nm_3.label(class="form-control-label") }}
                </div>
                <div class="col-75">
                        {{ form.rltd_dict_nm_3 }}
                </div>
                </div>
                <div class="row">
                    <div class='col-25'>
                    {{ form.rltd_dict_val_3.label(class="form-control-label") }}
                </div>
                <div class="col-75">
                    {{ form.rltd_dict_val_3 }}
                </div>
                </div>

                {% endif %}

            </fieldset>
            <div class="row">
                {{ form.submit(id="myBtn") }}
            </div>
        </form>
        </div>

        <script>
            dict_1_select = document.getElementById('rltd_dict_nm_1');
            dict_value_1_select = document.getElementById('rltd_dict_val_1');

            dict_1_select.onchange = function(){
                dict_id = dict_1_select.value;
                fetch('get_dict_values/' + dict_id).then(function(response){
                    response.json().then(function(data) {
                    optionHTML = '';
                    for (dict_values of data.dict_values) {
                        optionHTML += '<option value="' + dict_values.dict_val_id +'">' + dict_values.dict_val_val + '</option>'
                    }

                    dict_value_1_select.innerHTML = optionHTML;
                });

            });
        }

        dict_2_select = document.getElementById('rltd_dict_nm_2');
        dict_value_2_select = document.getElementById('rltd_dict_val_2');

        dict_2_select.onchange = function(){
                dict_id = dict_2_select.value;
                fetch('get_dict_values/' + dict_id).then(function(response){
                    response.json().then(function(data) {
                    optionHTML = '';
                    for (dict_values of data.dict_values) {
                        optionHTML += '<option value="' + dict_values.dict_val_id +'">' + dict_values.dict_val_val + '</option>'
                    }

                    dict_value_2_select.innerHTML = optionHTML;
                });

            });
        }

        dict_3_select = document.getElementById('rltd_dict_nm_3');
        dict_value_3_select = document.getElementById('rltd_dict_val_3');

        dict_3_select.onchange = function(){
                dict_id = dict_3_select.value;
                fetch('get_dict_values/' + dict_id).then(function(response){
                    response.json().then(function(data) {
                    optionHTML = '';
                    for (dict_values of data.dict_values) {
                        optionHTML += '<option value="' + dict_values.dict_val_id +'">' + dict_values.dict_val_val + '</option>'
                    }

                    dict_value_3_select.innerHTML = optionHTML;
                });

            });
        }
        </script>
        {% endblock content %}

app_4_website/templates/create_dict.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h1>{{ title }}</h1>
    </div>
    <div class="form">

 <form method = 'POST' action = "">
            {{ form.hidden_tag() }}
            <fieldset class = 'form-group'>
                    <div class="row">
                        <div class='col-25'>
                            {{ form.dict_tp.label(class="form-control-label") }}
                    </div>
                    <div class="col-75">
                      <select name="dict_tp">
                        <option value="1">Prosty</option>
                        <option value="2">Konwersji</option>
                        </select>
                        </div>
                    </div>

                <div class="row">
                    <div class='col-25'>
                        {{ form.dict_id.label(class="form-control-label") }}
                    </div>
                    <div class='col-75'>
                        <input class="form-control" id="disabledInput1" type="text" placeholder=" {{ dict_id }}" disabled>
                    </div>
                </div>

                <div class="row">
                    <div class='col-25'>
                    {{ form.dict_nm.label(class="form-control-label") }}
                </div>
                <div class='col-75'>
                    {{ form.dict_nm() }}
                    </div>
                </div>

                <div class="row">
                    <div class='col-25'>
                    {{ form.dict_desc.label(class="form-control-label") }}
                </div>
                <div class='col-75'>
                    {{ form.dict_desc }}
                    </div>
                </div>

                <div class="row">
                    <div class='col-25'>
                    {{ form.dict_crt_dt.label(class="form-control-label") }}
                </div>
                <div class='col-75'>
                        <input class="form-control" id="disabledInput2" type="text" placeholder=" {{ dict_crt_dt }}" disabled>
                    </div>
                </div>

            </fieldset>
            <div class="row">
                {{ form.submit(id="myBtn") }}
            </div>
        </form>
        </div>
        {% endblock content %}

app_4_website/templates/dict_details.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h1>{{ title }}</h1>
    </div>
    <div>
    <table>
        <thead>
        <th>DICT_VAL_CRT_DT</th>
        <th>DICT_VAL_ID</th>
        <th>DICT_VAL_VAL</th>
        {% if v_dict_tp == '2' %}
            <th>RLTD_DICT_NM_1</th>
            <th>RLTD_DICT_VAL_1</th>
            <th>RLTD_DICT_NM_2</th>
            <th>RLTD_DICT_VAL_2</th>
            <th>RLTD_DICT_NM_3</th>
            <th>RLTD_DICT_VAL_3</th>
        {% else %}
        {% endif %}
        <th class='option'>EDYTUJ</th>
        <th class='option'>USUN</th>
    </thead>
    <tbody>
    {% for item in v_val_list %}
    <tr>
        <td>{{ item.dict_val_crt_dt }}</td>
        <td>{{ item.dict_val_id }}</td>
        <td>{{ item.dict_val_val }}</td>
        {% if v_dict_tp == '2' %}
        <td>{{ item.rltd_dict_nm_1 }}</td>
        <td>{{ item.rltd_dict_val_1 }}</td>
        <td>{{ item.rltd_dict_nm_2 }}</td>
        <td>{{ item.rltd_dict_val_2 }}</td>
        <td>{{ item.rltd_dict_nm_3 }}</td>
        <td>{{ item.rltd_dict_val_3 }}</td>
        {% else %}
        {% endif %}
        <td class='option'>X</td>
        <td class='option'><a href="{{ url_for('dicts.remove_dict_value', p_dict_id=v_dict_id, p_dict_val_id=item.dict_val_id) }}"><i class="fas fa-trash"></i></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    <div>
        <a href="{{ url_for('dicts.add_dict_value', p_dict_id=v_dict_id) }}">Dodaj wpis</a>
    </div>
    {% endblock content %}

app_4_website/templates/dict_list.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h1>{{ title }}</h1>
    </div>
    <div>
    <table>
        <thead>
        <th>ID słownika</th>
        <th>Nazwa słownika</th>
        <th>Opis słownika</th>
        <th class="center">Typ słownika</th>
        <th class="center">Data utworzenia</th>
        <th class="option">Usuń</th>
        <th class="option">Edytuj</th>
    </thead>
    <tbody>
    {% for item in list %}
    <tr>
        <td>{{ item.dict_id }}</td>
        {% if item.dict_id == -3 %}
        <td> {{ item.dict_nm }}</td>
        {% else %}
        <td><a href="{{ url_for('dicts.dict_details', p_dict_id = item.dict_id) }}">{{ item.dict_nm }}</a></td>
        {% endif %}
        <td>{{ item.dict_desc }}</td>
        <td class="center">{{ item.dict_tp }}</td>
        <td class="center">{{ item.dict_crt_dt }}</td>
        <td class="option"><a href="{{ url_for('dicts.delete_dict', p_dict_id = item.dict_id) }}"><i class="fas fa-trash"></i></a></td>
        <td class="option">X</td>

    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    <div>
        <a href="{{ url_for('dicts.create_dict') }}">Dodaj słownik</a>
    </div>
    {% endblock content %}

app_4_website/templates/home.html
{% extends "index.html" %}
{% block content %}
<div class="bg2">
    <a href ="{{ url_for('balances.monthly_dtl_bal') }}">
    {% if monthly_bal['diff_bal'] > 0 %}
    <h2>{{ monthly_bal['diff_bal'] }} <span>zł</span></h2>
    {% else %}
    <h2>{{ monthly_bal['diff_bal'] }} <span>zł</span></h2>
    {% endif %}
      <p>DOCHÓD W MIESIĄCU: {{ monthly_bal['month'] }}</p>
    </a>
      </div>

  <div class="bg2">
    <a href ="#">
        <h2>{{ v_loaded_operation_dt }}</h2>
      <p> Ostatni zaczytany dzień </p>
    </a>
  </div>

  <div class="bg1">
     <a href ="{{ url_for('dicts.dict_list') }}">
      <h2><i class="fas fa-list-ul"></i></h2>
      <p>Słowniki</p>
    </a>
  </div>

  <div class="bg2">
    <a href ="{{ url_for('pocc.pty_oprtn_cd_clssfctn') }}">
      <h2><i class="fas fa-list-ul"></i></h2>
      <p>Kategoryzacja transakcji</p>
    </a>
  </div>

  <div class="bg2">
    <a class="yellow" href ="#">
        <h2><i class="fas fa-users"></i></h2>
      <p>Users</p>
    </a>
  </div>

  <div class="bg1">
    <a href ="{{ url_for('balances.yearly_dtl_bal') }}">
        {% if yearly_bal['diff_bal'] > 0 %}
    <h2>{{ yearly_bal['diff_bal'] }} <span>zł</span></h2>
    {% else %}
    <h2>{{ yearly_bal['diff_bal'] }} <span>zł</span></h2>
    {% endif %}
      <p>DOCHÓD W ROKU: {{ yearly_bal['year'] }}</p>
    </a>
  </div>

  <div class="bg2">
    <a href ="/">
        <h2><i class="fas fa-home"></i></h2>
      <p>Home</p>
    </a>
  </div>

  <div class="bg2">
    <a href ="#">
        <h2><i class="fas fa-balance-scale-left"></i></h2>
      <p>Balances</p>
    </a>
  </div>

  <div class="bg1">
    <a href ="#">
      <h2><i class="fas fa-chart-line"></i></h2>
      <p>Charts</p>
    </a>
  </div>

  <div class="bg1">
    <a href ="#">
      <h2><i class="fas fa-chart-pie"></i></h2>
      <p>Chart Pie</p>
    </a>
  </div>

  <div class="bg1">
    <a class="yellow" href ="#">
        <h2><i class="fas fa-users"></i></h2>
      <p>Users</p>
    </a>
  </div>

  <div class="bg1">
    <a href ="#" >
      <h2><i class="fas fa-list-ul"></i></h2>
      <p>List</p>
    </a>
  </div>
  {% endblock content %}

app_4_website/templates/monthly_dtl_bal.html
{% extends "index.html" %}
{% block content %}
<div class='table-chart'>
    <section class='head'>
        <div class='nav-menu'>
            <a onclick="history.back(-1)"><i class="far fa-arrow-alt-circle-left"></i></a>
            <a href='{{ url_for('main.home') }}'><i class="fas fa-home" alt="home"></i></a>
        </div>
        <div class='title'>
            <h1>{{ title }}</h1>
        </div>
    </section>

    <div class='table-content'>
        <table>
            <thead>
                <th>Data transakcji</th>
                <th>Odbiorca/Nadawca</th>
                <th>Typ Operacji</th>
                <th>Kwota</th>
                <th>Tytuł Transakcji</th>
                <th>Szczegóły Transakcji</th>
            </thead>
            <tbody>
                {% for item in v_list.items %}
                <tr>
                    <td>{{ item.TRANSACTION_DT }}</td>
                    <td>{{ item.PARTY_NM }}</td>
                    <td>{{ item.OPERATION_TP }}</td>
                    <td class="curr">{{ item.TRANSACTION_VAL }} {{ item.CURRENCY_NM }}</td>
                    {% if item.TRANSACTION_TITLE == '-3' %}
                    <td></td>
                    {% else %}
                    <td>{{ item.TRANSACTION_TITLE }}</td>
                    {% endif %}
                    {% if item.TRANSACTION_DTL_DESC == None %}
                    <td></td>
                    {% else %}
                    <td>{{ item.TRANSACTION_DTL_DESC }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class='paggination'>
            {% for page_num in v_list.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
            {% if v_list.page == page_num %}
            <a class="btn btn-paggination-active"
                href=" {{ url_for('balances.monthly_dtl_bal', p_year=p_year, p_month=p_month, page=page_num) }}">
                {{ page_num }}</a>
            {% else %}
            <a class="btn"
                href=" {{ url_for('balances.monthly_dtl_bal', p_year=p_year, p_month=p_month, page=page_num) }}">
                {{ page_num }}</a>
            {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class='chart-content'>
        <div class="chart-container">
            <canvas id="pie-chart"></canvas>
        </div>

        <div class="chart-container">
            TST TST TSTS
        </div>

        <script>
            new Chart(document.getElementById("pie-chart"), {
                type: 'pie',
                data: {
                    labels: {{ labels|tojson }},
                datasets: [{
                    label: "Pie Chart",
                    backgroundColor: {{ colors | tojson}},
                data: {{ values | tojson}}
                    }]
                  },
                options: {
                responsive: true,
                maintainAspectRatio: true,
                legend: {
                    position: 'right'
                },
                title: {
                    display: true,
                    text: 'Wydatki per kategoria'
                }
            }
                });
        </script>
    </div>
    {% endblock content %}

app_4_website/templates/pty_oprtn_cd_clssfctn.html
{% extends "index.html" %}
{% block content %}
<div class='table-options'>

    <section class='head'>
        <div class='nav-menu'>
            <a onclick="history.back(-1)"><i class="far fa-arrow-alt-circle-left"></i></a>
            <a href='{{ url_for('main.home') }}'><i class="fas fa-home" alt="home"></i></a>
        </div>
        <div class='title'>
            <h1>{{ title }}</h1>
        </div>
    </section>

    <section class="options">
        <form method='POST' action="">
            <div class="row">
                <div class="col-75">
                    <select id="pocc_select" name="pocc_select">
                        <option value="monthly" {% if p_year and p_month and not p_notfilled  %} selected {% endif %}>
                            Miesięczny</option>
                        <option value="yearly" {% if p_year and not p_month and not p_notfilled %} selected {% endif %}>
                            Roczny</option>
                        <option value="all" {% if not p_year and not p_month and not p_notfilled %} selected
                            {% endif %}>Wszystko</option>
                        <option value="notfilled" {% if not p_year and not p_month and p_notfilled %} selected
                            {% endif %}>Nie wypelnione</option>
                    </select>
                </div>
                <div class='col-25'>
                    <input type="submit" value="Wybierz" class='confirm'>
                </div>
            </div>
        </form>
        {% if p_year and p_month and not p_notfilled  %}
        {% endif %}
    </section>

    <div class='table-content'>
        <table>
            <thead>
                <th>PTY_NM</th>
                <th>OPRTN_TP_NM</th>
                <th>OPRTN_CTG</th>
                <th>TRNSCTN_CTG</th>
                <th>TRNSCT_SCTG</th>
                <th class='option'>EDYTUJ</th>
            </thead>
            <tbody>
                {% for item in v_val_list.items %}
                {% if item.trnsctn_ctg == -2 or item.trnsctn_sctg == -2 %}
                <tr class="unfilled">
                    {% else %}
                <tr>
                    {% endif %}
                    <td>{{ item.pty_nm }}</td>
                    <td>{{ item.dict_val_val }}</td>
                    <td>{{ item.oprtn_ctg }}</td>
                    {% if item.trnsctn_ctg == -2 %}
                    <td>{{ item.trnsctn_ctg }}</td>
                    {% else %}
                    <td>{{ item.trnsctn_ctg_val }}</td>
                    {% endif %}
                    {% if item.trnsctn_sctg == -2 %}
                    <td>{{ item.trnsctn_sctg }}</td>
                    {% else %}
                    <td>{{ item.trnsctn_sctg_val }}</td>
                    {% endif %}
                    <td class='option'><a
                            href="{{ url_for('pocc.pty_oprtn_cd_clsfctn_edit', p_pty_id=item.pty_id, p_oprtn_cd=item.oprtn_cd) }}">X</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class='paggination'>
            {% for page_num in v_val_list.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
            {% if v_val_list.page == page_num %}
            <a class="btn btn-paggination-active"
                href=" {{ url_for('pocc.pty_oprtn_cd_clssfctn', p_year=p_year, p_month=p_month, p_notfilled=p_notfilled, page=page_num) }}">
                {{ page_num }}</a>
            {% else %}
            <a class="btn"
                href=" {{ url_for('pocc.pty_oprtn_cd_clssfctn', p_year=p_year, p_month=p_month, p_notfilled=p_notfilled, page=page_num) }}">
                {{ page_num }}</a>
            {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

app_4_website/templates/tst.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h1>{{ title }}</h1>
    </div>
    <div>
    </div>
    {% endblock content %}

app_4_website/templates/yearly_dtl_bal.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h1>{{ title }}</h1>
    </div>
    <div>
        <table>
            <thead>
            <th>Miesiąc</th>
            <th>Dochód</th>
        </thead>
        <tbody>
    {% for item in v_list %}
        <tr>
            <td>{{ item.month }}</td>
            <td>{{ item.val_sum }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    {% endblock content %}